# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Public/Code/vhdl/rotatingProject/done_project_copied/done_project_copied.srcs/sources_1/ip/clocking/clocking.xci
# IP: The module: 'clocking' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Public/Code/vhdl/rotatingProject/done_project_copied/done_project_copied.gen/sources_1/ip/clocking/clocking_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clocking'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Public/Code/vhdl/rotatingProject/done_project_copied/done_project_copied.gen/sources_1/ip/clocking/clocking.xdc
# XDC: The top module name and the constraint reference have the same name: 'clocking'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Public/Code/vhdl/rotatingProject/done_project_copied/done_project_copied.gen/sources_1/ip/clocking/clocking_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clocking'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Public/Code/vhdl/rotatingProject/done_project_copied/done_project_copied.srcs/sources_1/ip/clocking/clocking.xci
# IP: The module: 'clocking' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Public/Code/vhdl/rotatingProject/done_project_copied/done_project_copied.gen/sources_1/ip/clocking/clocking_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clocking'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Public/Code/vhdl/rotatingProject/done_project_copied/done_project_copied.gen/sources_1/ip/clocking/clocking.xdc
# XDC: The top module name and the constraint reference have the same name: 'clocking'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Public/Code/vhdl/rotatingProject/done_project_copied/done_project_copied.gen/sources_1/ip/clocking/clocking_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clocking'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
