# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Public/Downloads/project_yuval/project_yuval/camera_project/done_project_copied.srcs/sources_1/ip/frame_buffer/frame_buffer.xci
# IP: The module: 'frame_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Public/Downloads/project_yuval/project_yuval/camera_project/done_project_copied.gen/sources_1/ip/frame_buffer/frame_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Public/Downloads/project_yuval/project_yuval/camera_project/done_project_copied.srcs/sources_1/ip/frame_buffer/frame_buffer.xci
# IP: The module: 'frame_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Public/Downloads/project_yuval/project_yuval/camera_project/done_project_copied.gen/sources_1/ip/frame_buffer/frame_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
